"""add user_email to requests

Revision ID: 3e249c8cbb2c
Revises: e89cdf3f693e
Create Date: 2025-07-23 23:40:29.691360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e249c8cbb2c'
down_revision: Union[str, None] = 'e89cdf3f693e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
