"""add carrier_name and carrier_email to requests

Revision ID: 47f62566bcfa
Revises: caeb8c0d0800
Create Date: 2025-07-25 00:47:49.007460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f62566bcfa'
down_revision: Union[str, None] = 'caeb8c0d0800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('carrier_name', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('carrier_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'carrier_email')
    op.drop_column('requests', 'carrier_name')
    # ### end Alembic commands ###
