"""add offer table

Revision ID: a38c335a7e16
Revises: 09ecdede5ac6
Create Date: 2025-07-16 23:17:24.453437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a38c335a7e16'
down_revision: Union[str, None] = '09ecdede5ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_from', sa.String(), nullable=True),
    sa.Column('route_to', sa.String(), nullable=True),
    sa.Column('flight_date', sa.String(), nullable=True),
    sa.Column('close_date', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.String(), nullable=True),
    sa.Column('rates', sa.String(), nullable=True),
    sa.Column('pickup_place', sa.String(), nullable=True),
    sa.Column('item_types', sa.String(), nullable=True),
    sa.Column('restrictions', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('urgent', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
