"""add carrier_phone and carrier_image to requests

Revision ID: af4df165c6cb
Revises: 47f62566bcfa
Create Date: 2025-07-25 14:58:33.821764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4df165c6cb'
down_revision: Union[str, None] = '47f62566bcfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('carrier_phone', sa.String(), nullable=True))
    op.add_column('requests', sa.Column('carrier_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'carrier_image')
    op.drop_column('requests', 'carrier_phone')
    # ### end Alembic commands ###
