"""add route table

Revision ID: b09fc5aba2b2
Revises: a38c335a7e16
Create Date: 2025-07-16 23:32:58.295894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09fc5aba2b2'
down_revision: Union[str, None] = 'a38c335a7e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_location', sa.String(), nullable=True),
    sa.Column('to_location', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('max_weight', sa.Integer(), nullable=True),
    sa.Column('item_types', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
