"""add source column to requests

Revision ID: caeb8c0d0800
Revises: 3e249c8cbb2c
Create Date: 2025-07-24 22:37:28.626791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caeb8c0d0800'
down_revision: Union[str, None] = '3e249c8cbb2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'source')
    # ### end Alembic commands ###
