"""add user_id to requests

Revision ID: db1c4fd7c8c1
Revises: 4443b50b8ccd
Create Date: 2025-07-23 23:14:48.935843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1c4fd7c8c1'
down_revision: Union[str, None] = '4443b50b8ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
