"""add user_email to requests

Revision ID: e89cdf3f693e
Revises: db1c4fd7c8c1
Create Date: 2025-07-23 23:26:09.660414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89cdf3f693e'
down_revision: Union[str, None] = 'db1c4fd7c8c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('user_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'user_email')
    # ### end Alembic commands ###
